# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WhatDo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WhatDo
  pod 'pop', '~> 1.0'
end
